# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('work_experience', models.TextField()),
                ('user', models.CharField(max_length=30)),
                ('vote_count', models.IntegerField(default=0)),
                ('profile_pic', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('comment_content', models.CharField(max_length=3000)),
                ('comment_time', models.DateTimeField(verbose_name='Comment Time')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=50)),
                ('nom_start_time', models.DateTimeField(verbose_name='Nominations start time')),
                ('nom_end_time', models.DateTimeField(verbose_name='Nominations end time')),
                ('vote_start_time', models.DateTimeField(verbose_name='Voting start time')),
                ('vote_end_time', models.DateTimeField(verbose_name='Voting end time')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Election'),
        ),
    ]
