# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('comment_content', models.CharField(max_length=3000)),
                ('comment_time', models.DateTimeField(verbose_name='Comment Time')),
                ('isCandidate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=50)),
                ('nom_start_time', models.DateTimeField(verbose_name='Nominations start time')),
                ('nom_end_time', models.DateTimeField(verbose_name='Nominations end time')),
                ('vote_start_time', models.DateTimeField(verbose_name='Voting start time')),
                ('vote_end_time', models.DateTimeField(verbose_name='Voting end time')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Election'),
        ),
    ]
