# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='candidateList',
            field=models.CharField(default='', max_length=500),
        ),
    ]
