# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
