# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0002_election_candidatelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=30)),
                ('work_experience', models.TextField()),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='election',
            name='candidateList',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Election'),
        ),
    ]
