# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0003_auto_20161107_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
    ]
