# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0006_candidate_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election_Portal.Election')),
            ],
        ),
    ]
