# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0007_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(),
        ),
    ]
