# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0009_candidate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='image',
        ),
    ]
