# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election_Portal', '0012_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
